export const tableMappings = [
  {
    sourceTable: 'TSIUSU',
    destinationTable: 'tgo_usuarios',
    primaryKey: 'sankhya_user_id', // This is the destination primary key
    sourcePrimaryKey: 'CODUSU',
    timestampColumn: 'DTALTER',
    columns: [
      { source: 'CODUSU', destination: 'sankhya_user_id' },
      { source: 'NOMEUSU', destination: 'username' },
      { source: 'NOMEUSUCPLT', destination: 'full_name' },
      { source: 'CONTACESSO', destination: 'access_control' },
      { source: 'EMAIL', destination: 'email' },
      { source: 'SENHA', destination: 'password_hash' },
      { source: 'NIVEL', destination: 'level' },
      { source: 'DTULTACESSO', destination: 'last_access_at' },
      { source: 'DTLIMACESSO', destination: 'access_limit_at' },
      { source: 'DTALTER', destination: 'sankhya_updated_at' },
      { source: 'CAIXA', destination: 'is_cashier' },
      { source: 'TEMECF', destination: 'has_ecf' },
      { source: 'IMPNFCENTRAL', destination: 'central_nf_printer' },
      { source: 'SERVIDORSMTP', destination: 'smtp_server' },
      { source: 'TIPOSMTP', destination: 'smtp_type' },
      { source: 'USUARIOSMTP', destination: 'smtp_username' },
      { source: 'SENHASMTP', destination: 'smtp_password' },
      { source: 'PERMEXPREL', destination: 'can_export_reports' },
      { source: 'ACESSOVISUALCAB', destination: 'can_view_all_headers' },
      { source: 'EXIBIRVALANALRENT', destination: 'show_profit_analysis' },
      { source: 'APROVCOT', destination: 'quote_approval_type' },
      { source: 'USER_NAME', destination: 'user_name_ad' },
      { source: 'CPF', destination: 'cpf' },
      { source: 'RG', destination: 'rg' },
      { source: 'DTNASC', destination: 'birth_date' },
      { source: 'CODFUNC', destination: 'function_code' },
      { source: 'INTERNO', destination: 'internal_code' },
      { source: 'NOMEFILA', destination: 'queue_name' },
      { source: 'SENHANUNCAEXPIRA', destination: 'password_never_expires' },
      { source: 'PORTASMTP', destination: 'smtp_port' },
      { source: 'SEGURANCASMTP', destination: 'smtp_security' },
      { source: 'EMAILSOLLIB', destination: 'email_sol_lib' },
      { source: 'NOTSLAFILA', destination: 'not_sla_queue' },
      { source: 'LOCALE', destination: 'locale' },
      { source: 'TIPOUSU', destination: 'user_type' },
      { source: 'AD_TELEFONECORP', destination: 'phone' },
      { source: 'AD_ENDERECO', destination: 'address' },
    ],
  },
  // Add other table mappings here
]
