// src/modules/sankhya/tsiusu/tsiusu.service.ts
import { getSqlServer } from '../../../config/sqlserver'
import logger from '../../../utils/logger'
import { SankhyaUserDetails } from './tsiusu.types'

export async function getUserDetails(codUsu: number): Promise<SankhyaUserDetails | undefined> {
  const query = `
    SELECT
      TSIUSU.CODUSU, TSIUSU.NOMEUSU, TSIUSU.EMAIL, TSIUSU.INTERNO, TSIUSU.CPF,
      TSIUSU.ABREGAVETA, TSIUSU.ACCOUNTDHEXPIRA, TSIUSU.ACCOUNTEMAIL, TSIUSU.ACCOUNTID,
      TSIUSU.ACCOUNTNOMEFOTO, TSIUSU.ACCOUNTPARTNER, '$$CLOBFIELD(TSIUSU.ACCOUNTTOKEN)$$' AS ACCOUNTTOKEN,
      TSIUSU.ACESSAFORMULAREL, TSIUSU.ACESSOPDVCANCITENS, TSIUSU.ACESSOPDVSANG,
      TSIUSU.ACESSOPDVSANGPDESP, TSIUSU.ACESSOPDVSUPR, TSIUSU.ACESSOVISUALCAB,
      TSIUSU.AD_AUTOPERAR1, TSIUSU.AD_AUTOPERAR2, TSIUSU.AD_AUTOPERAR3,
      TSIUSU.AD_AUTOPERAR4, TSIUSU.AD_AUTOPERAR5, TSIUSU.AD_AUTOPERAR6,
      TSIUSU.AD_AUTOPERAR7, TSIUSU.AD_AUTOSIRVO, TSIUSU.AD_CADEADOMOS,
      TSIUSU.AD_CODVEICULO, TSIUSU.AD_ENVIA_WPP, TSIUSU.AD_IDEXTERNO,
      TSIUSU.AD_MATMOSAIC, TSIUSU.AD_REABRIROS, TSIUSU.AD_RECEBENOTIFASO,
      TSIUSU.AD_RECEBENOTIFICACAO, TSIUSU.AD_TELEFONECORP, TSIUSU.ALTCTAFAT,
      TSIUSU.ALTCTAIMPBOL, TSIUSU.ALTORDCFECH, TSIUSU.APENASCOMPLIB,
      TSIUSU.APROVCOT, TSIUSU.ATUNUVERSAO, TSIUSU.AVISAVARPRECO,
      TSIUSU.BAIXADESP, TSIUSU.BAIXAREC, TSIUSU.CAIXA, TSIUSU.CODCARGAACESSO,
      TSIUSU.CODCENCUSPAD, TSIUSU.CODCONTATOPERFIL, TSIUSU.CODCTABCOINT,
      TSIUSU.CODCTABCOINT2, TSIUSU.CODEMP, TSIUSU.CODEMPNEGOC, TSIUSU.CODEQUIP,
      TSIUSU.CODETAPA, TSIUSU.CODFUNC, TSIUSU.CODGRUPO, TSIUSU.CODIDECONECT,
      TSIUSU.CODPARCPERFIL,
      (SELECT CONVERT(VARCHAR,FUN.CODCARGO) + ' - ' + CAR.DESCRCARGO
       FROM TFPFUN FUN
       JOIN TFPCAR CAR ON CAR.CODCARGO = FUN.CODCARGO
       WHERE FUN.CODEMP = TSIUSU.CODEMP AND FUN.CODFUNC = TSIUSU.CODFUNC) AS AD_CARGO,
      (SELECT CONVERT(VARCHAR,FUN.CODFUNCAO) + ' - ' + FCO.DESCRFUNCAO
       FROM TFPFUN FUN
       JOIN TFPFCO FCO ON FCO.CODFUNCAO = FUN.CODFUNCAO
       WHERE FUN.CODEMP = TSIUSU.CODEMP AND FUN.CODFUNC = TSIUSU.CODFUNC) AS AD_FUNCAO
    FROM TSIUSU
    WHERE TSIUSU.CODUSU = @codUsu
  `;
  try {
    const pool = await getSqlServer();
    const request = pool.request();
    request.input('codUsu', codUsu);
    const result = await request.query(query);
    logger.debug('getUserDetails executed', { codUsu, resultCount: result.recordset.length });
    return result.recordset[0] as SankhyaUserDetails | undefined;
  } catch (error: any) {
    logger.error('Error in getUserDetails', error, { codUsu });
    throw error;
  }
}
