export class Tgfpro {
  codprod: number;
  descrprod: string;
  compldesc: string | null;
  caracteristicas: string | null;
  referencia: string | null;
  codgrupoprod: number;
  marca: string | null;
  localizacao: string | null;
  codipi: number | null;
  classubtrib: number | null;
  marglucro: number | null;
  multipvenda: number | null;
  deccusto: number | null;
  decvlr: number | null;
  decqtd: number | null;
  comger: number | null;
  comvend: number | null;
  descmax: number | null;
  pesobruto: number;
  pesoliq: number;
  medaux: number | null;
  prazoval: number | null;
  agrupmin: number | null;
  qtdemb: number | null;
  alertaestmin: string;
  promocao: string;
  temicms: string;
  temiss: string;
  temipivenda: string;
  temipicompra: string;
  temirf: string;
  percirf: number | null;
  teminss: string;
  percinss: number;
  redbaseinss: number;
  usoprod: string | null;
  origprod: string | null;
  tipsubst: string | null;
  codicmsfast: number | null;
  tiplancnota: string | null;
  tipcontest: string | null;
  codtab: number | null;
  // imagem: Buffer | null; // Keep as Buffer for domain, convert in mapper
  ativo: string;
  estmax: number | null;
  estmin: number | null;
  apresdetalhe: string;
  selecionado: string | null;
  titcontest: string | null;
  liscontest: string | null;
  grupoicms: number | null;
  percaumentcusto: number | null;
  local: string | null;
  dtalter: Date;
  usalocal: string | null;
  homepage: string | null;
  codctactb2: number | null;
  codctactb3: number | null;
  temposerv: Date | null;
  endimagem: string | null;
  codusu: number;
  codprodroi: string | null;
  grupodescprod: string | null;
  refforn: string | null;
  hrdobrada: string;
  icmsgerencia: string;
  m3: number | null;
  temciap: string;
  implaudolote: string;
  codgar: number | null;
  codctactb4: number | null;
  dimensoes: string;
  percquebratec: number | null;
  codfiltro: number | null;
  endmodrotulo: string | null;
  codgenero: number | null;
  padrao: string;
  naturezaoperdes: string | null;
  cnae: number | null;
  solcompra: string;
  confere: string;
  remeter: string;
  motivoincexc: string | null;
  arredpreco: number | null;
  temcomissao: string;
  componobrig: string | null;
  fattotal: string | null;
  nometab: string | null;
  ap1Rctego: string;
  calculogiro: string;
  redbaseirf: number | null;
  altura: number | null;
  largura: number | null;
  espessura: number | null;
  unidade: string | null;
  codformaponta: number | null;
  confcegapeso: string;
  ordcalccustprod: number | null;
  regrawms: string;
  grupopis: string;
  grupocofins: string;
  grupocssl: string;
  cstipient: number | null;
  cstipisai: number | null;
  statusincexc: string | null;
  utilizawms: string;
  balanca: string;
  rendimento: string | null;
  obsetiqueta: string | null;
  codanp: number | null;
  codautcodif: string | null;
  codprodagrupapt: number | null;
  codprodagrupaptenc: number | null;
  cultura: string | null;
  cientifico: string | null;
  formulacao: string | null;
  concentracao: string | null;
  modoaplic: string | null;
  epocaaplic: string | null;
  manejoint: string | null;
  dosagem: number | null;
  voldosagem: string | null;
  dosagempor: number | null;
  voldosagempor: string | null;
  rendimentopr: string | null;
  receituario: string | null;
  exigebenefic: string | null;
  geraplaprod: string;
  aplicacao: number | null;
  intervalo: number | null;
  carencia: number | null;
  rendimentoha: number | null;
  produtonfe: number;
  tipgtinnfe: number;
  ncm: string | null;
  codvolplan: string | null;
  descmaxflex: number | null;
  acrescmax: number | null;
  flex: string;
  numitemrea: number | null;
  imprimir: string;
  confirmaimp: string;
  apuraprodepe: string | null;
  indespprodepe: string | null;
  qtdnflaudosint: number;
  codtribmuniss: string | null;
  tipcontestwms: string;
  listalpm: string;
  oneroso: string;
  refmercmed: string;
  termolabil: string;
  tempminima: number | null;
  tempmaxima: number | null;
  controlado: string;
  idenportaria: string | null;
  idenotc: string | null;
  idencorrelato: string;
  idencosme: string;
  prodfalta: string;
  statusmed: number;
  seqspr: number | null;
  seqsca: number | null;
  seqste: number | null;
  mvaajustado: number;
  infpureza: string;
  fabricante: string | null;
  usastatuslote: string;
  tamlote: number | null;
  tamserie: number | null;
  unidminarmaz: string | null;
  origemfat: string;
  usacodbarrasqtd: string;
  md5Paf: string | null;
  valcapm3: string;
  qtdpecafrac: string;
  utilordcorte: string;
  codprodperda: number | null;
  descrutilbem: string | null;
  impordemcorte: string;
  perctroca: number;
  corfontconspreco: number | null;
  corfundoconspreco: number | null;
  identimob: number | null;
  utilimob: number | null;
  temcredpiscofinsdepr: string;
  codprodinnatura: number | null;
  utilsmartcard: string;
  recupavaria: string;
  convervol: number | null;
  lastro: number | null;
  camadas: number | null;
  ordemmedida: number | null;
  aliqicmsintefd: number | null;
  codregmapa: string | null;
  apresform: string;
  codbarcomp: string;
  temmedicao: string;
  codfiltroreq: number | null;
  natbcpiscofins: string;
  contarporpeso: string;
  permcompprod: string;
  codexncm: number;
  qtdcst: number;
  diascst: number;
  perctolvarcst: number;
  qtdpedpend: number | null;
  leadtime: number | null;
  diasexpedicao: number | null;
  dtvaldif: string;
  shelflifemin: number | null;
  shelflife: number | null;
  codbarbalanca: string;
  valcbglobal: string;
  usapontos: string;
  percroyalty: number | null;
  integraeconect: string;
  enqreintegra: string;
  perccmtnac: number;
  perccmtimp: number;
  notifconf: string | null;
  usaseriefab: string | null;
  tipsernfe: string | null;
  vencompindiv: string | null;
  excluirconf: string | null;
  produzaut: string;
  usaimpagrupmin: string;
  rastrestoque: string;
  impetiqconf: string;
  vlrcomerc: number | null;
  vlrparcimpext: number | null;
  codfci: string | null;
  codativreintegra: string | null;
  servparaindust: string;
  cat1799Spres: string;
  aliqnac: number | null;
  aliqimp: number | null;
  descrprodnfe: string | null;
  geracustcompseg: string;
  estsegqtd: number;
  estsegdias: number | null;
  dtalteresq: Date | null;
  lotecompras: number | null;
  estmaxqtd: number;
  estmaxdias: number | null;
  dtalteremq: Date | null;
  desviomax: number;
  arredagrup: number;
  aplicasazo: string;
  lotecompminimo: number;
  agrupcompminimo: number;
  usaseriesepwms: string;
  topfaturcon: number | null;
  serfaturcon: string | null;
  exigelastrocamadas: string | null;
  fixoagenda: string;
  usalotedtval: string | null;
  usalotedtfab: string | null;
  exibcompexpkit: string;
  tiporeceitamod21: number | null;
  codprodsubst: number | null;
  dtsubst: Date | null;
  codcomp: number | null;
  natefdcontm410M810: number | null;
  perctolpesomaior: number | null;
  perctolpesomenor: number | null;
  codvolpesovar: string | null;
  usacontpesovar: string | null;
  perctolpesomaiorsep: number | null;
  perctolpesomenorsep: number | null;
  pctBf: number | null;
  przBf: number | null;
  controlmedic: string | null;
  perccmtfed: number;
  perccmtest: number;
  perccmtmun: number;
  codenqipient: number | null;
  codenqipisai: number | null;
  decvlrent: number | null;
  codespecst: number | null;
  descvenconsul: string | null;
  grupoicms2: number | null;
  mvapadrao: number | null;
  aliqgeral: number | null;
  codprodsubkit: number | null;
  tipokit: string | null;
  visivelappos: string | null;
  utilizaendflut: string | null;
  maxmulteconect: number | null;
  qtdidentif: number | null;
  tipoidentif: string | null;
  codvtp: number | null;
  impetiqsepwms: string | null;
  nroprocesso: string | null;
  tiposn: number | null;
  armazelote: string | null;
  temrastrolote: string;
  codanvisa: string | null;
  descranp: string | null;
  percmistglp: number | null;
  tipocontagem: string;
  percmistgnn: number | null;
  percmistgni: number | null;
  vlrpartidaglp: number | null;
  comercializacaoagri: string | null;
  obraconstcivil: number | null;
  classifcessaoobra: number | null;
  tipoinssespecial: string | null;
  percinssespecial: number | null;
  calcdifal: string;
  indescala: string | null;
  cnpjfabricante: string | null;
  codbenefnauf: string | null;
  codagregacao: string | null;
  qtdagrupamentomtz: number | null;
  codidcnae: number | null;
  codfiltrocta: number | null;
  forcaexpeconect: string | null;
  registrarpeso: string | null;
  desviomaxtolconfsep: number | null;
  desviomintolconfsep: number | null;
  servprestter: string | null;
  fragmentalote: string | null;
  percredbaseicmsefet: number | null;
  nuversaoimg: number | null;
  integrafox: number | null;
  nuversao: number | null;
  motisencaoanvisa: string | null;
  codnbs: string | null;
  consprodcat42: string | null;
  tipoitemsped: string | null;
  incpesobruto: number | null;
  incpesoliquido: number | null;
  nurfe: number | null;
  mvaoriginaldrcst: number | null;
  tamanhomediopeca: number | null;
  percentseppul: number | null;
  atunuversao: string | null;
  gradepadrao: string | null;
  aliqfethab: number | null;
  obtstantmedent: string | null;
  descproddrcst: string | null;
  participaadrcst: string | null;
  mvaoriginaladrcst: number | null;
  aliqfecop: number | null;
  prodsujfecop: string | null;
  desdesccalcpis: string | null;
  aliqinternacat42: number | null;
  conestorigprod: string | null;
  gerimpnretreinfaq: string | null;
  prodaliadrcst: string | null;
  tiputilcom: number | null;
  prodinterno: string | null;
  calcfustpro: string | null;
  calcfunttelpro: string | null;
  codbardifgtin: string | null;
  codbartribdifgtin: string | null;
  codnatpamcard: number | null;
  usanrofogo: string | null;
  nufop: number | null;
  tipcargarepom: string | null;
  tipcargapamcard: string | null;
  tipcargaefrete: string | null;
  tpcargamdfe: string | null;
  tipcargapb: string | null;
  adObscesta: string | null;
  wmsprodrastsermed: string | null;
  statusncm: string | null;
  adCapacidade: string | null;
  adDescrcomplemento: string | null;
  bloqvendafrac: string | null;
  adPercpipe: number | null;
  adDtvalca: Date | null;
  adLimiteusu: number | null;
  tpirrfext: number | null;
  codnatrend: number | null;
  adQtdfixo: string | null;
  indtiprefbcicmsst: string | null;
  codvolkanban: string | null;
  calrupturaestoque: string | null;
  percindmistura: number | null;
  opeexpfethab: string | null;
  opeintestfethab: string | null;
  opeintfethab: string | null;
  servdespntrib: string | null;
  codigonfcom: string | null;
}
