export class Tsiusu {
  codusu: number;
  nomeusu: string | null;
  contacesso: string | null;
  dtlimacesso: Date | null;
  interno: string | null;
  codfunc: number | null;
  email: string | null;
  optgat: string | null;
  vlrmaxaut: number | null;
  nivel: number;
  dtalter: Date;
  caixa: string;
  servidorsmtp: string | null;
  tiposmtp: string | null;
  usuariosmtp: string | null;
  senhasmtp: string | null;
  nomefila: string | null;
  dtultimasenha: Date | null;
  senhanuncaexpira: string | null;
  temecf: string;
  topbaixareceita: number | null;
  topbaixadespesa: number | null;
  baixarec: string | null;
  baixadesp: string | null;
  altctafat: string;
  altctaimpbol: string;
  rendiasvaljur: number | null;
  vercabpropria: string;
  portasmtp: number;
  segurancasmtp: string;
  altordcfech: string;
  exibirvalanalrent: string;
  aprovcot: string;
  userName: string | null;
  codetapa: number | null;
  contagol: string | null;
  dtultacesso: Date | null;
  emailsollib: string | null;
  notslafila: string | null;
  cpf: string | null;
  rg: string | null;
  nomeusucplt: string | null;
  dtnasc: Date | null;
  impnfcentral: string;
  codusualter: number | null;
  nomeusualter: string | null;
  minutosfin: number;
  acessovisualcab: string;
  restringecart: string;
  verimpcurs: string;
  excliborc: string;
  locale: string;
  foto: Buffer | null;
  permexprel: string;
  toleranciaacesso: number | null;
  visacesoutusu: string;
  apenascomplib: string;
  impsep: string | null;
  acessaformularel: string;
  integraeconect: string;
  infrecsen: string | null;
  avisavarpreco: string;
  nivelacesso: string | null;
  permaltmoeda: string | null;
  permimprimerel: string;
  instalapacotess: string;
  infbiomdig: string | null;
  ignorahorascruz: string;
  senhaeconect: number | null;
  codideconect: string | null;
  idperfileconect: string | null;
  permreperro: string;
  selectwcapo: string;
  proprietario: string | null;
  operacional: string | null;
  implantador: string | null;
  gestor: string | null;
  codperfil: number | null;
  nuversao: number | null;
  timvertodasfacs: string | null;
  timpathscanner: string | null;
  timbaixaword: string | null;
  usurede: string | null;
  gruporede: string | null;
  ignoraldap: string | null;
  timbaixtitrecabe: string;
  atunuversao: string | null;
  accountdhexpira: Date | null;
  accounttoken: string | null;
  accountid: string | null;
  accountnomefoto: string | null;
  accountemail: string | null;
  tokencheckout: string | null;
  acessopdvcancitens: string | null;
  acessopdvsang: string | null;
  acessopdvsupr: string | null;
  acessopdvsangpdesp: string | null;
  tipenvnotsol: string | null;
  liberacredito: string | null;
  codempnegoc: number | null;
  podealterarpef: string | null;
  adIdexterno: string | null;
  adRecebenotificacao: string | null;
  adReabriros: string | null;
  adAutosirvo: string | null;
  adRecebenotifaso: string | null;
  accountpartner: number | null;
  tipousu: number;
  imp2Sansupcai: string;
  abregaveta: string | null;
  adCadeadomos: string | null;
  adAutoperar1: string | null;
  adAutoperar2: string | null;
  adAutoperar3: string | null;
  adAutoperar4: string | null;
  adAutoperar5: string | null;
  adAutoperar6: string | null;
  adAutoperar7: string | null;
  desctotalnotapdv: string | null;
  adTelefonecorp: string | null;
  adMatmosaic: string | null;
  adEnviaWpp: string | null;
}
