import { Tsiufs } from '../../tsiufs/domain/tsiufs.domain';

export class Tsicid {
  codcid: number;
  uf: number | null;
  nomecid: string;
  ddd: string | null;
  distancia: number | null;
  dtalter: Date;
  descricaocorreio: string | null;
  seqentrega: number | null;
  populacao: number | null;
  codmunfis: number | null;
  vlrfretemin: number | null;
  vlrfreteton: number | null;
  tipofrete: string;
  vlrfretekm: number | null;
  vlrtaxaent: number | null;
  codmunsiafi: number | null;
  codmundms: number | null;
  vendamin: number | null;
  latitude: string | null;
  longitude: string | null;
  codmundief: number | null;
  qtddiassub: number;
  qtdsub: number;
  temsubstitnfse: string;
  tipcancnfse: string;
  vlrlimcancnfse: number | null;
  motcancsubnfse: string | null;
  metarredvlriss: string | null;
  maxnotalotenfse: number | null;
  nfsetemplatesubst: string;
  tipocnae: number | null;
  nuversao: number | null;
  linkagua: string | null;
  linkenergia: string | null;
  linkiptu: string | null;
  noformatlc116: string | null;
  cnaefullnfse: string | null;
  noinscmunpar: string | null;
  gercodnatissjson: string | null;
  envitenssepjson: string | null;
  qtdmaxenvitensjson: number | null;
  obsjsonenotas: string | null;
  permcancnfsesubstit: string | null;
  jsonsemalidenmun: string | null;
  vminretencaoiss: number | null;
  actcanexnt: string | null;
  remzeroesquerdlc116: string | null;
  envfpjson: string | null;
  infqtdvlrunijson: string | null;
  envmulemailjson: string | null;
  atunuversao: string | null;
  envtagdesconjson: string | null;
  gernunfseinfcpm: string | null;
  mascaralc116: string | null;
  gercnaemultjson: string | null;
  regesptrib: string | null;
  envcodigonbsjson: string | null;
}
