import { Tgfpro } from '../../tgfpro/domain/tgfpro.domain';

export class Tgfite {
  nutab: number | null;
  nunota: number;
  sequencia: number;
  codemp: number;
  codprod: number;
  controle: string;
  usoprod: string;
  qtdneg: number;
  qtdentregue: number;
  qtdconferida: number;
  vlrunit: number | null;
  vlrtot: number | null;
  vlrcus: number | null;
  baseipi: number;
  vlripi: number;
  aliqipi: number | null;
  baseicms: number;
  aliqicms: number | null;
  vlricms: number;
  vlrdesc: number;
  basesubstit: number;
  vlrsubst: number;
  pendente: string;
  codtrib: number | null;
  atualestoque: number;
  observacao: string | null;
  reserva: string;
  statusnota: string;
  faturar: string | null;
  vlrrepred: number;
  vlrdescbonif: number;
  percdesc: number;
  m3: number | null;
  adMotBonifica: string | null;
  adDescmax: number | null;
  aliqicmsred: number | null;
  dtalter: Date | null;
  custo: number | null;
  basesubstsemred: number | null;
  solcompra: string | null;
  codtribiss: number | null;
  codcfps: number | null;
  aliqiss: number | null;
  qtdformula: number | null;
  atualestterc: string | null;
  percdescbonif: number | null;
  terceiros: string | null;
  endimagem: string | null;
  altura: number | null;
  largura: number | null;
  espessura: number | null;
  qtdpeca: number | null;
  precobase: number | null;
  vlracrescdesc: number | null;
  vlrretencao: number | null;
  cstipi: number | null;
  perccom: number | null;
  vlrcom: number | null;
  altpreco: string | null;
  qtdfixada: number | null;
  perccomger: number | null;
  vlrcomger: number | null;
  qtdwms: number | null;
  basicmmod: number | null;
  basicmstmod: number | null;
  qtdfat: number | null;
  basestufdest: number | null;
  vlricmsufdest: number | null;
  basestant: number | null;
  produtonfe: string | null;
  gtinnfe: string | null;
  gtintribnfe: string | null;
  codpromo: number | null;
  vlrpromo: number | null;
  vlrliqprom: number | null;
  precobaseqtd: number | null;
  retdatacritica: string | null;
  percpureza: number | null;
  percgermin: number | null;
  nupromocao: number | null;
  percdescprom: number | null;
  vlrptopureza: number | null;
  codantecipst: string | null;
  numpedido: number | null;
  seqpedido: number | null;
  csosn: number | null;
  numpedido2: string | null;
  seqpedido2: string | null;
  statuslote: string | null;
  qtdvol: number | null;
  serieinicial: string | null;
  seriefinal: string | null;
  dtinicio: Date | null;
  hrinicio: number | null;
  hrfim: number | null;
  vlrunitdolar: number | null;
  peso: number | null;
  md5Paf: string | null;
  baseiss: number | null;
  vlriss: number | null;
  vlrtroca: number | null;
  variacaofcp: number | null;
  dtfim: Date | null;
  tempogasto: number | null;
  desviopadrao: number | null;
  perctroca: number | null;
  percdescdigitado: number | null;
  percdesctgfdes: number | null;
  sequenciafiscal: number | null;
  vlrdescdigitado: number | null;
  percvc: number | null;
  codmotdesoneraicms: number | null;
  variacao: number | null;
  atualestindividual: string | null;
  vlrstextranota: number | null;
  ulocetpaestind: string | null;
  origprod: string | null;
  nrseriereserva: string | null;
  vlrunitloc: number | null;
  vlricmsant: number | null;
  basesubstitant: number | null;
  vlrsubstant: number | null;
  numeroos: number | null;
  percdescbase: number | null;
  cancelado: string | null;
  grupofat: number | null;
  numcontrato: number | null;
  idaliqicms: number | null;
  vlrunitmoe: number;
  vlrdescmoe: number;
  vlrtotmoe: number;
  codvolparc: string | null;
  codenqipi: number | null;
  codespecst: number | null;
  vlrdescrat: number | null;
  basesubstitunitorig: number | null;
  vlrsubstunitorig: number | null;
  geraproducao: string;
  codagregacao: string | null;
  indescala: string | null;
  cnpjfabricante: string | null;
  basestfcpintant: number | null;
  vlrstfcpintant: number | null;
  percstfcpintant: number | null;
  codbenefnauf: string | null;
  origembusca: string | null;
  produtopesquisado: number | null;
  aliqstextranota: number | null;
  basestextranota: number | null;
  qtdtribexport: number | null;
  codproinfo: string | null;
  aliqstfcpstant: number | null;
  vlrvendapromo: number | null;
  vlrrepredsemdesc: number | null;
  coddocarrecad: number | null;
  numdocarrecad: string | null;
  vlricmsdiferido: number | null;
  tiposeparacao: string | null;
  basecalcstextranota: number | null;
  redbasest: number | null;
  marglucro: number | null;
  percredvlripi: number | null;
  idaliqicmsdificms: number | null;
  tipentrega: string | null;
  aliqfethab: number | null;
  vlrfethab: number | null;
  idaliqicmsat: number | null;
  baseicmsat: number | null;
  aliqicmsat: number | null;
  aliqintericmsat: number | null;
  vlricmsat: number | null;
  iddescparceria: number | null;
  vlrdescparceria: number | null;
  percusaqudecpe: number | null;
  vlrcusaqudecpe: number | null;
  baseicmsstfrete: number | null;
  icmsstfrete: number | null;
  vlrrepredst: number | null;
  codsit08Efd: string | null;
  tiputilcom: number | null;
  unidade: string | null;
  aliqfust: number | null;
  basefust: number | null;
  vlrfust: number | null;
  aliqfunttel: number | null;
  basefunttel: number | null;
  vlrfunttel: number | null;
  codmotdesonerast: number | null;
  controledesttms: string | null;
  adVlrkm: number | null;
  adAplicacao: string | null;
  codbarrapdv: string | null;
  adEmpreito: string | null;
  adSituacaoprodcot: string | null;
  percusaqudecpeest: number | null;
  codfci: string | null;
  adTag: number | null;
  adDtfabricacao: Date | null;
  adNucertificado: string | null;
  codipi: number | null;
  idaliqiss: number | null;
  indrepdes: string | null;
  codnatrend: number | null;
  adRatreabilidade: string | null;
  adMedidas: string | null;
  codigonfcom: string | null;
  inddevolucaonfcom: string;
  // Related product
  produto: Tgfpro | null;
}
